rmcs_executor:
  ros__parameters:
    update_rate: 1000.0

    components:
      - rmcs_core::hardware::Gantry -> gantry


gantry:
  ros__parameters:
    # C Board
    # 没有实物，暂时留空
    board_serial: ""

    # 龙门架目标速度
    #
    # 正值：一个方向
    # 负值：反方向
    # 0：停止
    target_velocity: 5.0

    # 左右双电机同步系数
    sync_coefficient: 0.2

    # MatrixPidCalculator<2>
    kp: 1.0
    ki: 0.0
    kd: 0.5