rmcs_executor:
  ros__parameters:
    update_rate: 1000.0
    components:
      - rmcs_core::hardware::Gantry -> gantry
      - rmcs_core::controller::gantry::GantryController -> gantry_controller
      - rmcs_core::controller::pid::PidController -> gantry_left_pid
      - rmcs_core::controller::pid::PidController -> gantry_right_pid

gantry:
  ros__parameters:
<<<<<<< HEAD
=======

>>>>>>> 849704d55a23fcce944d7076dc6523db3b12371a
    board_serial: ""
    reduction_ratio: 19.2
    lead_screw: 0.01

<<<<<<< HEAD
gantry_controller:
  ros__parameters:
    target_position: 0.3
    max_velocity: 0.15
    sync_gain: 2.5
    max_sync_error: 0.008
    position_min: -0.4
    position_max: 0.4

gantry_left_pid:
  ros__parameters:
    setpoint: /gantry/cmd_vel_left
    measurement: /gantry/left_motor/velocity
    control: /gantry/left_motor/control_torque
    kp: 8.0
    ki: 0.2
    kd: 0.1
    integral_min: -10.0
    integral_max: 10.0
    output_min: -24.0
    output_max: 24.0

gantry_right_pid:
  ros__parameters:
    setpoint: /gantry/cmd_vel_right
    measurement: /gantry/right_motor/velocity
    control: /gantry/right_motor/control_torque
    kp: 8.0
    ki: 0.2
    kd: 0.1
    integral_min: -10.0
    integral_max: 10.0
    output_min: -24.0
    output_max: 24.0
=======

    target_velocity: 5.0


    sync_coefficient: 0.2

    # MatrixPidCalculator<2>
    kp: 1.0
    ki: 0.0
    kd: 0.5
>>>>>>> 849704d55a23fcce944d7076dc6523db3b12371a
